### ISSUE TITLE
Possible to add INFO command?

### ISSUE THREAD

**Issue by aleksraiden** [alash3al/redix#12]
Hi, lot of thanks about your work! 
I try to use redix with NodeJS app and using popular client module, node_redis. But his architecture needed to use INFO command when obtain client connection. And we cant used it with Redix: 

Redix error!
{ ReplyError: Ready check failed: unknown commands [info]
    at parseError (/opt/tendermint/app/node_modules/redis-parser/lib/parser.js:193:12)
    at parseType (/opt/tendermint/app/node_modules/redis-parser/lib/parser.js:303:14) command: 'INFO' }

Can you add this command with base support of redis-compartability?

**Comment by alash3al** [comment]
It's my pleasure that many of developers start using/testing redix, anyway, I'll release a version today that includes `hkeys`, `keys [<pattern>]`, `info`, `echo`.

If you have any other requirements, just ping me

**Comment by alash3al** [comment]
@aleksraiden , [v1.7](https://github.com/alash3al/redix/releases/tag/v1.7) is now available with the mentioned commands as well as `RATELIMIT` commands!
