### ISSUE TITLE
benchmark

### ISSUE THREAD

**Issue by RegulusStar** [alash3al/redix#14]
redis-benchmark -n 1000000 -t set,get -P 16 -q

Intel(R) Xeon(R) CPU E5-2682 v4 @ 2.50GHz  2 Core 
4G RAM 
SSDB Disk

redis-5.0.3
SET: 548245.62 requests per second
GET: 671140.94 requests per second

redix V1.7
SET: 6992.27 requests per second
GET: 188323.92 requests per second

redix V1.8 (use leveldb  _-engine=level_)
SET: 166334.00 requests per second
GET: 280190.53 requests per second

ssdb 1.9.7
SET: 34694.52 requests per second
GET: 35812.77 requests per second

**Comment by alash3al** [comment]
Thank you @RegulusStar 

Could you try it with the new engine in `v1.8` `redix -engine=level`?
> `level` is using leveldb, and I think that it is faster

**Comment by alash3al** [comment]
> Using `redix -engine=level`

```bash
# redis
➜ redis-benchmark -n 1000000 -t set,get -P 16 -p 6379 -q
SET: 287687.00 requests per second
GET: 316455.69 requests per second

# redix
➜ redis-benchmark -n 1000000 -t set,get -P 16 -p 6380 -q 
SET: 137816.98 requests per second
GET: 235626.77 requests per second
```

**Comment by Tazeg** [comment]
Could you use level as default ?

**Comment by alash3al** [comment]
In my opinion, we should keep redix versions compatible with each other.

**Comment by alash3al** [comment]
I'll try to perform aggressive optimization in redix to achieve more speed, but we won't achieve redis speed easily because `redis = ram`, but `redix = disk`, and `ram` is faster than `disk`.

But `redix` isn't limited to `ram`
