### ISSUE TITLE
the release 1.8 version label show error in cli

### ISSUE THREAD

**Issue by withu2018** [alash3al/redix#16]
the release 1.8 version label show error in cli
`redix server version: 1.7`

MacBookPro 2018 16G Mem 512G ssd
` redis-benchmark -n 1000000 -t set,get -P 16 -p 6380 -q
SET: 323519.88 requests per second
GET: 1078748.62 requests per second`

very good

_Originally posted by @withu2018 in https://github.com/alash3al/redix/issue_comments#issuecomment-451419162_

**Comment by alash3al** [comment]
Just redownload it again :)

Are you using `--engine=level`?

**Comment by alash3al** [comment]
I'm trying to make v1.9 much more faster, I don't know whether I'll do it or not, but I'm trying ...

**Comment by withu2018** [comment]
Thank you very much for providing such an excellent program.

I think the current level engine is fast enough, as long as it follows redis closely and completes all redis functions. And achieve long-term operation stability, no memory leakage and other issues.

There are also optimizations compatible with redis client tools.

Of course, you are the leader of the project. We respect your direction.

**Comment by alash3al** [comment]
Thank you, 

No worries bro,  just tell me your opinions
