### ISSUE TITLE
FLUSHDB

### ISSUE THREAD

**Issue by slava-vishnyakov** [alash3al/redix#19]
Redix is awesome! Thanks!

Would it be possible to implement [FLUSHDB](https://redis.io/commands/FLUSHDB) / [FLUSHALL](https://redis.io/commands/flushall) to delete everything in selected db / all dbs?

Thanks!

**Comment by withu2018** [comment]
Need

**Comment by alash3al** [comment]
Implementing ...

**Comment by alash3al** [comment]
Here you go,

https://github.com/alash3al/redix/releases/tag/v1.10

Test and give me feedback

**Comment by slava-vishnyakov** [comment]
@alash3al Awesome! Thank you!

**Comment by slava-vishnyakov** [comment]
@alash3al FLUSHDB works as expected, however FLUSHALL doesn't seem to do anything.

```
127.0.0.1:6380[5]> flushall
OK
127.0.0.1:6380[5]> hlen keys
(integer) 3418
```

**Comment by alash3al** [comment]
@slava-vishnyakov could you redownload and test it again?

**Comment by slava-vishnyakov** [comment]
@alash3al Now it works! 🎊   Thank you! 👍

**Comment by slava-vishnyakov** [comment]
@alash3al Oh, wait, scratch that. Still doesn't work somehow.

Maybe it has something to do with how I launch it? ` ./redix_darwin_amd64 -engine=leveldb `

```
127.0.0.1:6380[5]> flushall
OK
127.0.0.1:6380[5]> hlen keys
(integer) 15577
127.0.0.1:6380[5]> flushdb
OK
127.0.0.1:6380[5]> hlen keys
(integer) 0
```

**Comment by alash3al** [comment]
Oh, sorry, it was due to caching, I was removing the DB(s) from disk, not from the cache too,
I think it should be fine now if you redownloaded it again,

**Comment by slava-vishnyakov** [comment]
Awesome! Yep, that works!

```
127.0.0.1:6380[5]> hlen keys
(integer) 5515
127.0.0.1:6380[5]> flushall
OK
127.0.0.1:6380[5]> hlen keys
(integer) 0
```

Thank you!
