### ISSUE TITLE
command line params change

### ISSUE THREAD

**Issue by withu2018** [alash3al/redix#22]
1. can't find the version cmd
2.-engine  default  leveldb, at version 1.8 ,the string is level or badger
![image](https://user-images.githubusercontent.com/2484480/55124869-c1a4b880-5142-11e9-8440-61610deee826.png)

3.口
![image](https://user-images.githubusercontent.com/2484480/55124927-fd3f8280-5142-11e9-925a-45734867d799.png)

4. in php7.1.27  [get] cmd error. the "+" before returning the data
![image](https://user-images.githubusercontent.com/2484480/55125147-c1f18380-5143-11e9-98c5-881ac58fe49c.png)

**Comment by withu2018** [comment]
expire abc 30
unknown commands [expire]

**Comment by alash3al** [comment]
1- there is no version CMD
2- now redix deals with leveldb as level, boltdb as bolt, and so on (just re-download the 1.10 again)
3- that square chars, related to windows cmd, it works perfectly on unix systems
4- I'll check that

**Comment by withu2018** [comment]
Can these functions be added?
