### ISSUE TITLE
the first data stored in list is not correct data.

### ISSUE THREAD

**Issue by kekek** [alash3al/redix#25]
the first data in list by lpush is not correct! It like this belllow.
![image](https://user-images.githubusercontent.com/4726765/59200072-01b7fb00-8bca-11e9-970c-32b4deaae30c.png)

this is my correct data .
![image](https://user-images.githubusercontent.com/4726765/59200107-14cacb00-8bca-11e9-99df-accddb5ae2a8.png)

is this the right way i used lpush. I really don't konw.

**Comment by alash3al** [comment]
![Screen Shot 2019-06-10 at 4 37 08 PM](https://user-images.githubusercontent.com/3078292/59203030-0c5c9b00-8b9e-11e9-8069-cabd72eb777b.png)

the first pic in your issue seems that you inserted a hex encoded string not a json string

**Comment by kekek** [comment]
I had instered my data by   [redis-client for go](github.com/garyburd/redigo/redis), and got the result. This is my code after : 
```
func setListData(code string, sig sync.Signal, val []string) error {
	db := storage.Redis().Get()
	defer db.Close()

	key := getListDataKey(code, sig)

	args := []interface{}{key}
	for i := range val {
		args = append(args, val[i])
	}
	_, err := redis.ByteSlices(db.Do("LPUSHU", args...))
	if err != nil {
		return err
	}

	return nil
}
```
May be I'll test this tomorrow to find what happend

**Comment by kekek** [comment]
I test this from redis-cli and got the same result.
![image](https://user-images.githubusercontent.com/4726765/59205526-b0156d80-8bd5-11e9-8f68-4c8f6a4f9761.png)

May be this is caused by different version. This is the envriment.
```

OS : Macos Darwin Kernel Version 16.0.0
redis-cli : 3.2.3
redix-server [docker images]:  alash3al/redix                          latest              8b51be953c19        5 months ago        438MB
```
