### ISSUE TITLE
Does redix support replication or clustering feature?

### ISSUE THREAD

**Issue by lvqian** [alash3al/redix#26]

**Comment by alash3al** [comment]
Sorry for very late reply, 

I'm planning to restructure redix to include built-in replication/clustering/sharding!

**Comment by lvqian** [comment]
thanks for reply, looking forward to the new feature!

**Comment by joe-getcouragenow** [comment]
@alash3al This does what you need: https://github.com/mkawserm/flamed

Its badgerDB with RAFT under it, using pebble engine. no CGO.

Let me know if you have any questions.
