### ISSUE TITLE
Invalid strorage engine badger specified

### ISSUE THREAD

**Issue by Zuckonit** [alash3al/redix#28]
➜  redix ./redix_darwin_amd64 -engine badger
Invalid strorage engine specified

version: redix server version: 1.10
os: macos

**Comment by Zuckonit** [comment]
find out the issue: use badgerdb instead of badger.

problem happens at readme
```
-engine string
        the storage engine to be used, available (default "badger")
```

https://github.com/alash3al/redix/blob/master/vars.go#L113

**Comment by Zuckonit** [comment]
https://github.com/alash3al/redix/pull/29

**Comment by mtchuyen** [comment]
Sorry to open its

Run:
`./redix -workers 1 -engine badgerdb`

Result:

```
⇨ redix server version: 1.10 
⇨ redix selected engine: badgerdb 
⇨ redix workers count: 1 
⇨ redix resp server available at: :6380 
⇨ redix http server available at: :7090 
```

And test:

```
./redis-cli -h 127.0.0.1 -p 6380
127.0.0.1:6380> set kk-col 1
(error) db error: Error Creating Dir: "redix-data/badger/0": mkdir redix-data/badger/0: no such file or directory
127.0.0.1:6380> 
```
But, I run with `leveldb` is OK.

Pls help me!

Thanks.
