### ISSUE TITLE
Ha

### ISSUE THREAD

**Issue by gedw99** [alash3al/redix#3]
How can I standup 2 of these and have them stay in sync ?

Wondering if redcon would help ?

**Comment by alash3al** [comment]
HA is very simple nowadays, even if the feature doesn't exists in the software itself, redis cluster could be used or any alternative out there,  I built redix based on redis protocol to make use of redis ecosystem. 

May I make HA a native feature in redix in the next releases.

**Comment by gedw99** [comment]
Thanks for that.

What about a simple event sourcing pattern Inn golang ?
It's simply logging all mutations before they hit Redis and just replay them onto each redis database. Because of concurrency this would only be reliable in Master to Slave.

Am guessing for multi master a raft approach would be needed but it would be dog slow.

**Comment by gedw99** [comment]
Hey @alash3al 
I noticed your using redcon. The same authour also has https://github.com/tidwall/finn that is a nice Raft system with flexible backend like yours.

https://github.com/tidwall/finn/blob/master/finn.go#L22
