### ISSUE TITLE
No permissions to pull

### ISSUE THREAD

**Issue by ficapy** [alash3al/redix#41]
```
docker pull ghcr.io/alash3al/redix                                                                                               ✘  15:19:47
Using default tag: latest
Error response from daemon: unauthorized
```

maybe make it publicly readable?

**Comment by c-nv-s** [comment]
I am experiencing the same issue. please can you make it public

**Comment by alash3al** [comment]
I don't know how, but I didn't set any privacy settings seems you have to login to github registry using docker cli?

**Comment by c-nv-s** [comment]
```
# docker pull ghcr.io/alash3al/redix
Using default tag: latest
Error response from daemon: Head "https://ghcr.io/v2/alash3al/redix/manifests/latest": unauthorized
```

I don't receive this error for other people's projects that use ghcr so it must be a setting you have on somewhere

**Comment by c-nv-s** [comment]
@markphelps tagging you in on this because I saw mentioned you are on the ghcr team from this message https://github.com/k3s-io/k3s/issues/2401#issuecomment-717948014 
please could you advise if this issue is actually resolved?

**Comment by alash3al** [comment]
I did a search but I didn't find anything, if the repo is public then you can pull it, if there is a setting that I don't see anyone tell me where is it?

**Comment by alash3al** [comment]
thanks @markphelps I'll check it

**Comment by alash3al** [comment]
@c-nv-s You can test pulling it now

**Comment by c-nv-s** [comment]
@alash3al yes now it works. Thank you

**Comment by alash3al** [comment]
@c-nv-s You're welcome,

Could you tell me why you're using redix not redis?

**Comment by c-nv-s** [comment]
because I am trying to minimize the number of storage backends for the services I need to run my applications.
as redix stores to postgres I can essentially eliminate redis and mongodb (via FerretDB) which gives me considerably simplified stack to manage :-)
