### ISSUE TITLE
availability of v1 branch?

### ISSUE THREAD

**Issue by c-nv-s** [alash3al/redix#42]
Hi I am actually still keen on using version 1 of this repo which had some very useful features, but it seems that branch is no longer available?
Is it possible to keep that version available somewhere else?
I noted that ``docker pull alash3al/redix`` does pull the old version and so ``docker pull ghcr.io/alash3al/redix`` is needed for v5

**Comment by alash3al** [comment]
to be honest I may not be able to maintain multiple versions, but you can tell me which features you liked and let me think with you how it could be achieved

**Comment by c-nv-s** [comment]
you are under no obligation to maintain the original version, but it would be useful to still have the source code available for people who wish to use, debug and improve on it.
You can put it in a new repository and set it to "archived" so that it will be clear there are no expectations for future work :-)

**Comment by c-nv-s** [comment]
> to be honest I may not be able to maintain multiple versions, but you can tell me which features you liked and let me think with you how it could be achieved

like I mentioned here: https://github.com/alash3al/redix/discussions/39#discussioncomment-1974577
those features are killer so if you want my biased opinion on what you should work on next in v5, there you go.

**Comment by alash3al** [comment]
Great, thanks for your response and support

**Comment by c-nv-s** [comment]
I was going to mention that for the ``WEBHOOKSET <channel> <httpurl>,`` command, it would actually be really useful if you could somehow allow the user to set a header/s that will be added to the webhook call.
This is because most receiving apps will need some form of ``X-API-Token``,``X-Authorization`` etc

**Comment by alash3al** [comment]
Good addon,

by the way I added the support for pub/sub (v5.2.0), so I can add this feature again.

**Comment by c-nv-s** [comment]
amazing! I'll pull the latest version.
thanks again for this project. I really appreciate it.

**Comment by alash3al** [comment]
@c-nv-s thanks for your support

**Comment by c-nv-s** [comment]
>I was going to mention that for the WEBHOOKSET <channel> <httpurl>, command, it would actually be really useful if you could somehow allow the user to set a header/s that will be added to the webhook call.
This is because most receiving apps will need some form of X-API-Token,X-Authorization etc

Is it ok if I raise a ticket for this feature? because it will be very useful for me soon.

**Comment by c-nv-s** [comment]
> > I was going to mention that for the WEBHOOKSET  , command, it would actually be really useful if you could somehow allow the user to set a header/s that will be added to the webhook call.
> > This is because most receiving apps will need some form of X-API-Token,X-Authorization etc
> 
> Is it ok if I raise a ticket for this feature? because it will be very useful for me soon.

Ticket raised because I need this to integrate with some workflow automation tools.
