### ISSUE TITLE
`go build` raise errors

### ISSUE THREAD

**Issue by lylex** [alash3al/redix#9]
When I run `go build` in the project, it raises errors:

```
# github.com/alash3al/redix/kvstore/bolt
kvstore/bolt/bolt.go:13:2: imported and not used: "go.etcd.io/bbolt" as bolt
kvstore/bolt/bolt.go:18:17: undefined: bbolt
```

```
# github.com/alash3al/redix
./commands_utils.go:23:10: assignment mismatch: 2 variables but 1 values
./init.go:27:3: undefined: "github.com/dgraph-io/badger".SetLogger
```

So looks like we have 3 issues here:

1. `go.etcd.io/bbolt` imported as bolt(defined in the package), but never used. Considering kvstore/bolt/bolt.go package is also named bolt, we rename it to 'bbolt'
1. `satori/go.uuid` v1.2.0 `uuid.NewV4()` returns only one value
1. `dgraph-io/badger` v1.5.4 does not contains the method SetLogger, remove it.

**Comment by alash3al** [comment]
Thank you @lylex , seems that this is a versioning issues, because it is working with users and other users not, I'll accept that pr, and update the read me that a user should set `GO111MODULE=on` env.

**Comment by alash3al** [comment]
@lylex , I updated go mod files again ...
